//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace WebGame.UI.Blazor.Services
{
    public interface IClient
    {
        HttpClient HttpClient { get; }
        bool ReadResponseAsString { get; set; }

        Task<ICollection<GetAllEnemiesViewModel>> ArenaAsync();
        Task<ICollection<GetAllEnemiesViewModel>> ArenaAsync(CancellationToken cancellationToken);
        Task<ICollection<GetAllArmorsViewModel>> ArmorsAsync();
        Task<ICollection<GetAllArmorsViewModel>> ArmorsAsync(CancellationToken cancellationToken);
        Task<DuelPlayerVsEnemyResponse> DuelAsync(int enemyId);
        Task<DuelPlayerVsEnemyResponse> DuelAsync(int enemyId, CancellationToken cancellationToken);
        Task<ICollection<GetAllJobsViewModel>> JobsAllAsync();
        Task<ICollection<GetAllJobsViewModel>> JobsAllAsync(CancellationToken cancellationToken);
        Task JobsDELETEAsync(int id);
        Task JobsDELETEAsync(int id, CancellationToken cancellationToken);
        Task<GetJobViewModel> JobsGETAsync(int id);
        Task<GetJobViewModel> JobsGETAsync(int id, CancellationToken cancellationToken);
        Task<int> JobsPOSTAsync(CreateJobCommand body);
        Task<int> JobsPOSTAsync(CreateJobCommand body, CancellationToken cancellationToken);
        Task<LoginCommandResponse> LoginAsync(LoginCommand body);
        Task<LoginCommandResponse> LoginAsync(LoginCommand body, CancellationToken cancellationToken);
        Task LogoutAsync();
        Task LogoutAsync(CancellationToken cancellationToken);
        Task<ICollection<GetAllMissionsViewModel>> MissionsAllAsync();
        Task<ICollection<GetAllMissionsViewModel>> MissionsAllAsync(CancellationToken cancellationToken);
        Task MissionsDELETEAsync(int id);
        Task MissionsDELETEAsync(int id, CancellationToken cancellationToken);
        Task<GetMissionViewModel> MissionsGETAsync(int id);
        Task<GetMissionViewModel> MissionsGETAsync(int id, CancellationToken cancellationToken);
        Task<int> MissionsPOSTAsync(CreateMissionCommand body);
        Task<int> MissionsPOSTAsync(CreateMissionCommand body, CancellationToken cancellationToken);
        Task<GetPlayerViewModel> PlayerAsync(int id);
        Task<GetPlayerViewModel> PlayerAsync(int id, CancellationToken cancellationToken);
        Task<CreateUserCommandResponse> RegisterAsync(CreateUserCommand body);
        Task<CreateUserCommandResponse> RegisterAsync(CreateUserCommand body, CancellationToken cancellationToken);
        Task ShopAsync();
        Task ShopAsync(CancellationToken cancellationToken);
        Task UpdateJobAsync(UpdateJobCommand body);
        Task UpdateJobAsync(UpdateJobCommand body, CancellationToken cancellationToken);
        Task UpdateMissionAsync(UpdateMissionCommand body);
        Task UpdateMissionAsync(UpdateMissionCommand body, CancellationToken cancellationToken);
        Task<ICollection<GetAllWeaponsViewModel>> WeaponsAdminAsync();
        Task<ICollection<GetAllWeaponsViewModel>> WeaponsAdminAsync(CancellationToken cancellationToken);
        Task<ICollection<GetAllWeaponsViewModel>> WeaponsAsync();
        Task<ICollection<GetAllWeaponsViewModel>> WeaponsAsync(CancellationToken cancellationToken);
        Task<ICollection<GetAllWeaponsViewModel>> WeaponsAuthAsync();
        Task<ICollection<GetAllWeaponsViewModel>> WeaponsAuthAsync(CancellationToken cancellationToken);
    }
}